apiVersion: apps/v1

kind: Deployment

metadata:

  name: golangtodolist

  labels:

    app: golangtodolist

spec:

  replicas: 1

  selector:

    matchLabels:

      app: golangtodolist

  template:

    metadata:

      labels:

        app: golangtodolist

    spec:

      containers:

      - name: golangtodolist

        image: adrame98/golangtodolist:v1.0.2

        ports:

        - containerPort: 9091

        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "golangTodoList"
          - name: DB_USER
            value: "root"
          - name: APP_LISTENING_ADDRESS
            value: "0.0.0.0"
          - name: APP_PORT
            value: "9091"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysecret
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysecret
