apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangtodolist
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: gotodo
        image: adrame98/golangtodolist:v1.0.1
        ports:
        - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: go-service
    protocol: TCP
    port: 80
    targetPort: 80